### PR TITLE
Format and lint with Ruff

### PR DESCRIPTION
**Pull request by theodore-s-beers**
Can roll this back if needed, but I think it should be helpful.

NB, there's a function that was defining a `return_vars` list and then not returning anything. I added the `return` statement, but I had some other doubt as to the correctness of the function. Might be something for @jagar2 or @JGoddy to look into.

### CODE REVIEW

**Comment by theodore-s-beers** [comment]
The problematic function was/is `get_return_variables` in `src/datafed_torchflow/pytorch.py`.

**Comment by theodore-s-beers** [comment]
I'm going to merge this despite intermittent CI failures. I'm not sure what's going wrong with the runner; it sometimes fails early, on the step where it fetches the Git repo.

**Comment by JGoddy** [comment]
@theodore-s-beers Thanks for figuring this out! Yes, the  `get_return_variables` function in `src/datafed_torchflow/pytorch.py` should have the return function you added; it must have gotten removed when I copied it from somewhere else. What doubt did you have regarding the correctness of this function? Also, this function should be in  `src/datafed_torchflow/utils.py`, not `src/datafed_torchflow/pytorch.py`, unless you want me to put the functions from `utils.py` back into `pytorch.py` as static methods.

**Comment by theodore-s-beers** [comment]
My remaining doubt was about the `pass` statement. Why even have that branch if it does nothing?

**Comment by theodore-s-beers** [comment]
Also, re: code organization, that's totally up to you and Josh. I don't think I moved anything. (My problem at the moment is that CI/CD is all messed up…)

**Comment by JGoddy** [comment]
Good catch! That is also an old version of that function. I just created a new branch with the latest version in the `utils.py` file.  Sorry to hear the CI/CD is all messed up.

**Pull request merged**
